name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Enable magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Terraform fmt
        run: nix-shell --run 'terraform fmt -check -recursive ./terraform'
      - name: Terraform init
        run: |
          nix-shell --run '
            for dir in $(find terraform -type d); do
              echo "initializing dir $dir"
              terraform -chdir=$dir init -backend=false
            done
          '
      - name: Terraform validate
        run: |
          nix-shell --run '
            for dir in $(find terraform -type d); do
              echo "validating dir $dir"
              terraform -chdir=$dir validate -no-color
            done
          '

  NixFormatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check nixpkgs-fmt formatting
        run: nix develop --command sh -c "git ls-files '*.nix' | xargs nixpkgs-fmt --check"

  Spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: codespell-project/codespell-problem-matcher@v1
    - name: Check Spelling
      run: nix develop --command codespell --ignore-words-list .
